import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import QueryProviders from '@/providers/QueryProviders';
import Sidebar from '@/app/components/sidebar/Sidebar';
import Header from '@/app/components/header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg">
        <QueryProviders>
          <div className="home-grid">
            <div className={''}>
              <Sidebar />
            </div>
            <main className={'relative'}>
              <Header />
              <div className="px-2 mt-[70px]">{children}</div>
            </main>
          </div>
        </QueryProviders>
      </body>
    </html>
  );
}
